{% set name = "lightfm" %}
{% set version = "1.15" %}
{% set sha256 = "7dc3fd48f0ef32c7e8de8e38b2bbe7063b56b570c702453d7467b43b413f6806" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    # Pin numpy at build time with the minimum version available.
    - numpy         # [not win]
    - numpy         # [win]
    - scipy >=0.17
    - requests
  run:
    - python
    - {{ pin_compatible('numpy') }}   # [not win]
    - {{ pin_compatible('numpy') }}   # [win]
    - scipy >=0.17
    - requests

test:
  imports:
    # ensure OpenMP backend is used on linux
    - lightfm._lightfm_fast_openmp  # [linux]
    - lightfm
    - lightfm.lightfm

about:
  home: https://github.com/lyst/lightfm
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A Python implementation of LightFM, a hybrid recommendation algorithm.'

  description: |
      LightFM is a Python implementation of a number of popular recommendation
      algorithms for both implicit and explicit feedback, including efficient
      implementation of BPR and WARP ranking losses. It's easy to use,
      fast (via multithreaded model estimation), and produces high quality results.
  doc_url: http://lyst.github.io/lightfm/docs/home.html
  dev_url: https://github.com/lyst/lightfm

extra:
  recipe-maintainers:
    - maciejkula
    - rth
